### ISSUE TITLE
Triplets File Significantly Larger than Corpus

### ISSUE THREAD

**Issue by Helw150** [vered1986/LexNET#10]
Hello!

I'm trying to generate the triplets path file, but I've run into something that feels a little strange and just want to make sure it's not a sign of an error. 

My input corpus is around 20Gb in size, however, at present, the output pair file is 64G and still increasing in size. Perhaps it was naive of me, but I was expecting the triplets file to be similar in size or even smaller than the corpus. Was this an incorrect assumption?

**Comment by vered1986** [comment]
Hi William,

I'm having a bit of a problem to tell you the exact file size right now because the server I used doesn't currently work, but the zipped version of the final db files that I have is around 85Gb. It's normal that the size of the file is larger than the size of the corpus, because I split each sentence to multiple paths (given that it contains a word from the vocabulary, and the vocabulary is very large), and I also create satellite paths (duplicate paths with words before and after the original path). There is always also the case of using the different spacy version. At some point it was producing too many paths. In case it doesn't stop soon or become too large, I suggest using a smaller vocabulary and maybe not to create the satellites.

**Comment by Helw150** [comment]
Thank you so much - as long as it's sane that the triplets file is larger than the corpus I have the info I need. The specifics of the file size aren't neccesary.
