### ISSUE TITLE
Please provide requirements.txt 

### ISSUE THREAD

**Issue by ablx** [vered1986/LexNET#6]
Hi,
I would like to know which version of spacy you are using.
Can you please provide the requirements.txt?

Greetings
Mirco

**Comment by vered1986** [comment]
Hi Mirco,

Sorry for the late reply. 

In [V2](https://github.com/vered1986/LexNET/tree/v2), I think you can use any spaCy version, but I last tested it with version [1.6](https://github.com/explosion/spaCy/releases/tag/v1.6.0). If you use it with another version and encounter any issues, do let me know! (I expect spaCy v2 to be extremely slow, though).

In the paper I originally used version 0.99, which can be used in [v1 branch](https://github.com/vered1986/LexNET/tree/v1). I changed the code due to major changes in spaCy that affected the performance of LexNET (see here: https://github.com/vered1986/HypeNET/issues/2).

Best,
Vered

**Comment by ablx** [comment]
Thanks for the information, I didn't encouter any problems yet, just getting a different parse tree for the example in the HypeNet paper
